$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: aml-register-cli
version: 0.3.0
description: Environment for model registration component with Azure CLI
image: mcr.microsoft.com/azure-cli:latest
conda_file: conda.yaml
