$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: aml-register-sdk
version: 1.0.0
description: Environment for model registration component with Azure ML SDK
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
conda_file: conda.yaml
